export const DEFAULT_SETTINGS = {
    hotel_name: 'Hotel Margarita Real',
    hotel_timezone: 'America/Caracas',
    default_currency: 'USD',
    igtf_rate: '0.03',
    iva_rate: '0.00',
    early_checkin_surcharge: '0.50',
    late_checkout_surcharge: '0.50',
    allow_partial_payments: 'true',
    checkin_time: '14:00',
    checkout_time: '12:00',
    require_phone: 'true',
    max_upload_size_mb: '2',
    date_format: 'dd/mm/yyyy',
};